# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(418, 604)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 70, -1, -1)
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ageEdit = QtWidgets.QLineEdit(Dialog)
        self.ageEdit.setObjectName("ageEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ageEdit)
        self.label_8 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.phoneEdit = QtWidgets.QLineEdit(Dialog)
        self.phoneEdit.setObjectName("phoneEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.phoneEdit)
        self.label_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.addressEdit = QtWidgets.QLineEdit(Dialog)
        self.addressEdit.setObjectName("addressEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.addressEdit)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.HRComboBox = QtWidgets.QComboBox(Dialog)
        self.HRComboBox.setObjectName("HRComboBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.HRComboBox)
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label)
        self.serviceSelection = QtWidgets.QComboBox(Dialog)
        self.serviceSelection.setObjectName("serviceSelection")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.serviceSelection)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.defaultButton = QtWidgets.QPushButton(Dialog)
        self.defaultButton.setObjectName("defaultButton")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.defaultButton)
        self.taxEdit = QtWidgets.QLineEdit(Dialog)
        self.taxEdit.setReadOnly(False)
        self.taxEdit.setPlaceholderText("")
        self.taxEdit.setObjectName("taxEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.taxEdit)
        self.payMethod = QtWidgets.QComboBox(Dialog)
        self.payMethod.setObjectName("payMethod")
        self.payMethod.addItem("")
        self.payMethod.addItem("")
        self.payMethod.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.payMethod)
        self.saleEdit = QtWidgets.QLineEdit(Dialog)
        self.saleEdit.setObjectName("saleEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.saleEdit)
        self.label_9 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tạo mới đơn hàng"))
        self.label_3.setText(_translate("Dialog", "Họ Và Tên"))
        self.label_4.setText(_translate("Dialog", "Tuổi"))
        self.label_8.setText(_translate("Dialog", "Số ĐT"))
        self.label_7.setText(_translate("Dialog", "Địa chỉ"))
        self.label_5.setText(_translate("Dialog", "Người tạo"))
        self.label_6.setText(_translate("Dialog", "Ngày tạo"))
        self.label.setText(_translate("Dialog", "Dịch Vụ"))
        self.label_2.setText(_translate("Dialog", "Thanh Toán"))
        self.defaultButton.setText(_translate("Dialog", "Default"))
        self.payMethod.setItemText(0, _translate("Dialog", "-"))
        self.payMethod.setItemText(1, _translate("Dialog", "Online"))
        self.payMethod.setItemText(2, _translate("Dialog", "Tiền Mặt"))
        self.label_9.setText(_translate("Dialog", "Phương thức"))
        self.label_10.setText(_translate("Dialog", "Chiết Khấu"))
        self.label_11.setText(_translate("Dialog", "Thuế"))
