# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(893, 641)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 30, -1, -1)
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.newIDButton = QtWidgets.QPushButton(Dialog)
        self.newIDButton.setCheckable(True)
        self.newIDButton.setChecked(False)
        self.newIDButton.setFlat(False)
        self.newIDButton.setObjectName("newIDButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.newIDButton)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setClearButtonEnabled(True)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ageEdit = QtWidgets.QLineEdit(Dialog)
        self.ageEdit.setClearButtonEnabled(True)
        self.ageEdit.setObjectName("ageEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ageEdit)
        self.label_8 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.phoneEdit = QtWidgets.QLineEdit(Dialog)
        self.phoneEdit.setClearButtonEnabled(True)
        self.phoneEdit.setObjectName("phoneEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.phoneEdit)
        self.label_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.addressEdit = QtWidgets.QLineEdit(Dialog)
        self.addressEdit.setClearButtonEnabled(True)
        self.addressEdit.setObjectName("addressEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.addressEdit)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_9 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.saleEdit = QtWidgets.QLineEdit(Dialog)
        self.saleEdit.setClearButtonEnabled(True)
        self.saleEdit.setObjectName("saleEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.saleEdit)
        self.label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.taxEdit = QtWidgets.QLineEdit(Dialog)
        self.taxEdit.setReadOnly(False)
        self.taxEdit.setPlaceholderText("")
        self.taxEdit.setClearButtonEnabled(True)
        self.taxEdit.setObjectName("taxEdit")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.taxEdit)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.idDisplay = QtWidgets.QLabel(Dialog)
        self.idDisplay.setText("")
        self.idDisplay.setObjectName("idDisplay")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idDisplay)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.defaultButton = QtWidgets.QPushButton(Dialog)
        self.defaultButton.setObjectName("defaultButton")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.defaultButton)
        self.label_12 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.searchEdit = QtWidgets.QLineEdit(Dialog)
        self.searchEdit.setObjectName("searchEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.searchEdit)
        self.searchButton = QtWidgets.QPushButton(Dialog)
        self.searchButton.setObjectName("searchButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.searchButton)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.applyButton = QtWidgets.QPushButton(Dialog)
        self.applyButton.setObjectName("applyButton")
        self.verticalLayout.addWidget(self.applyButton)
        self.noteArea = QtWidgets.QScrollArea(Dialog)
        self.noteArea.setMaximumSize(QtCore.QSize(16777215, 250))
        self.noteArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.noteArea.setWidgetResizable(False)
        self.noteArea.setObjectName("noteArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 429, 248))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.noteArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.noteArea)
        self.sumUpLabel = QtWidgets.QLabel(Dialog)
        self.sumUpLabel.setMinimumSize(QtCore.QSize(20, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sumUpLabel.setFont(font)
        self.sumUpLabel.setObjectName("sumUpLabel")
        self.verticalLayout.addWidget(self.sumUpLabel)
        self.payButton = QtWidgets.QPushButton(Dialog)
        self.payButton.setCheckable(True)
        self.payButton.setObjectName("payButton")
        self.verticalLayout.addWidget(self.payButton)
        self.payEdit = QtWidgets.QLineEdit(Dialog)
        self.payEdit.setObjectName("payEdit")
        self.verticalLayout.addWidget(self.payEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.searchEdit, self.searchButton)
        Dialog.setTabOrder(self.searchButton, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.newIDButton)
        Dialog.setTabOrder(self.newIDButton, self.nameEdit)
        Dialog.setTabOrder(self.nameEdit, self.ageEdit)
        Dialog.setTabOrder(self.ageEdit, self.phoneEdit)
        Dialog.setTabOrder(self.phoneEdit, self.addressEdit)
        Dialog.setTabOrder(self.addressEdit, self.lineEdit_2)
        Dialog.setTabOrder(self.lineEdit_2, self.defaultButton)
        Dialog.setTabOrder(self.defaultButton, self.saleEdit)
        Dialog.setTabOrder(self.saleEdit, self.taxEdit)
        Dialog.setTabOrder(self.taxEdit, self.textEdit)
        Dialog.setTabOrder(self.textEdit, self.tableView)
        Dialog.setTabOrder(self.tableView, self.applyButton)
        Dialog.setTabOrder(self.applyButton, self.noteArea)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tạo mới đơn hàng"))
        self.newIDButton.setText(_translate("Dialog", "NEW ID (F4)"))
        self.newIDButton.setShortcut(_translate("Dialog", "F4"))
        self.label_3.setText(_translate("Dialog", "Họ Và Tên"))
        self.label_4.setText(_translate("Dialog", "Tuổi"))
        self.label_8.setText(_translate("Dialog", "Số ĐT"))
        self.label_7.setText(_translate("Dialog", "Địa chỉ"))
        self.label_5.setText(_translate("Dialog", "Người tạo"))
        self.label_6.setText(_translate("Dialog", "Ngày tạo"))
        self.label_9.setText(_translate("Dialog", "Thanh Toán"))
        self.label_10.setText(_translate("Dialog", "Chiết Khấu"))
        self.label_11.setText(_translate("Dialog", "Thuế"))
        self.label.setText(_translate("Dialog", "ID Khách Hàng"))
        self.label_2.setText(_translate("Dialog", "ID Đơn Hàng"))
        self.defaultButton.setText(_translate("Dialog", "Default (Ctrl+D) "))
        self.defaultButton.setShortcut(_translate("Dialog", "Ctrl+D"))
        self.label_12.setText(_translate("Dialog", "Ghi Chú"))
        self.searchEdit.setPlaceholderText(_translate("Dialog", "SEARCH BY PHONE NUMBER"))
        self.searchButton.setText(_translate("Dialog", "Search and Paste (F3)"))
        self.searchButton.setShortcut(_translate("Dialog", "F3"))
        self.dateTimeEdit.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy h:mm:ss"))
        self.applyButton.setText(_translate("Dialog", "Apply (F5)"))
        self.applyButton.setShortcut(_translate("Dialog", "F5"))
        self.sumUpLabel.setText(_translate("Dialog", "Tổng Tiền Gốc:"))
        self.payButton.setText(_translate("Dialog", "Thanh toán tại chỗ"))
        self.payEdit.setPlaceholderText(_translate("Dialog", "VND"))
